{{- if .Values.security.zookeeper.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka.fullname" . }}-zoo-client-cert-ks-pwd
stringData:
  password: {{ .Values.security.zookeeper.certificate.keystores.password }}
{{- end }}

