{{- if .Values.security.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zookeeper.fullname" . }}-cert-ks-pwd
stringData:
  password: {{ .Values.security.certificate.keystores.password }}
{{- end }}

