{{- if .Values.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "test-client.fullname" . }}-broker
spec:
  secretName: {{ include "test-client.fullname" . }}-broker-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    size: 2048
    algorithm: RSA
  usages:
    - client auth
  commonName: KafkaClient
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password
        name: {{ include "test-client.fullname" . }}-broker-cert-ks-pwd
  dnsNames:
    - '{{ include "test-client.fullname" . }}'
  issuerRef:
    name: {{ .Values.caIssuer.name }}
    kind: Issuer
    group: cert-manager.io
{{- end }}
