{{- if .Values.enabled }}
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: {{ include "test-client.fullname" . }}
  name: {{ include "test-client.fullname" . }}
spec:
  containers:
  - command:
    - tail
    - -f
    - /dev/null
    image: {{ .Values.image }}
    name: {{ include "test-client.fullname" . }}
    imagePullPolicy: Never
    volumeMounts:
      - name: kafka-certs
        mountPath: "/certs/broker"
        readOnly: true
      - name: test-files
        mountPath: /tests
  terminationGracePeriodSeconds: 2
  volumes:
    - name: test-files
      configMap:
        name: {{ include "test-client.fullname" . }}-test
    - name: kafka-certs
      secret:
        secretName: {{ include "test-client.fullname" . }}-broker-cert
        items:
          - key: truststore.jks
            path: truststore.jks
          - key: keystore.jks
            path: keystore.jks

{{- end }}
