{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "test-client.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "test-client.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "test-client.fullname" . }}-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "test-client.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: {{ .Values.image }}
        name: {{ include "test-client.fullname" . }}
        imagePullPolicy: Never
        volumeMounts:
          - name: kafka-certs
            mountPath: "/certs/broker"
            readOnly: true
          - name: test-files
            mountPath: /tests
      terminationGracePeriodSeconds: 2
      volumes:
        - name: test-files
          configMap:
            name: {{ include "test-client.fullname" . }}-test
        - name: kafka-certs
          secret:
            secretName: {{ include "test-client.fullname" . }}-broker-cert
            items:
              - key: truststore.jks
                path: truststore.jks
              - key: keystore.jks
                path: keystore.jks
    
{{- end }}
